#! /bin/sh

sxhkd &

PANEL_HEIGHT=28
WINDOW_GAP=5

bspc config border_width         2
bspc config bottom_padding $PANEL_HEIGHT
bspc config window_gap $WINDOW_GAP

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc config initial_polarity second_child

bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
bspc rule -a thunderbird desktop="^9"

bspc monitor -d 1 2 3 4 5 6 7 8 9
