#!/usr/bin/env bash

SETTING_FILE="/tmp/.show_battery_$(whoami)"
PERCENT_REGEX=": ([Disc|C].+), ([0-9]{1,3})\%"

is_enabled() {
	return $([[ ! -f "$SETTING_FILE" ]])
}

toggle() {
	if is_enabled; then
		touch "$SETTING_FILE"
	else
		rm -f "$SETTING_FILE"
	fi
}

print_message() {
	if (($charging)); then
		echo -n ''
	else
		if (($percent < 10)); then
			echo -n ''
		elif (($percent < 40)); then
			echo -n ''
		elif (($percent < 75)); then
			echo -n ''
		elif (($percent < 90)); then
			echo -n ''
		else
			echo -n ''
		fi
	fi

	(($show_percent)) && echo " $percent%" || echo
}

print_colour() {
	if (($charging)); then
		echo "#3498db"
	else
		echo $(python2 -c "import colorsys; import math; print('#%02x%02x%02x' % tuple(map(lambda x: x*255, colorsys.hsv_to_rgb(math.floor($percent * 120. / 100.) / 255., 0.7, 1.))))")
	fi
}

[[ $BLOCK_BUTTON = "3" ]] && toggle

show_percent=0; is_enabled && show_percent=1;

if [[ ! $(acpi -b) =~ $PERCENT_REGEX ]]; then
	echo Bad acpi output
	exit 1
fi

charging=0
[[ ${BASH_REMATCH[1]} = "Charging" ]] && charging=1
percent="${BASH_REMATCH[2]}"

for i in {1..2}; do print_message; done
print_colour
