#!/usr/bin/env python2
from datetime import datetime as date
import os

def init_exams():
    exams = []

    def add_exam(day, name, loc, morning, month=5):
        exams.append({
            'date': date(2016, month, day, 9 if morning else 14, 30 if morning else 0),
            'name': name,
            'location': loc,
            'time': "AM" if morning else "PM"
            })

    add_exam(03, 'Prof Comp', 'Avon Room: 80', True)
    add_exam(04, 'SSC', 'New Gym: 85', False)
    add_exam(06, 'Security', 'New Gym: 58', False)
    add_exam(11, 'Maths', 'Avon Room: 146', True)
    add_exam(16, 'Models', 'New Gym: 75', True)
    add_exam(18, 'CSA', 'Sports Hall: 75', True)
    add_exam(31, 'NLP', 'Arts 201: 18', False)
    add_exam(02, 'Vision', 'Avon Room: 131', True, month=6)

    return exams


exams = init_exams()

try:
    next_exam = next(e for e in exams if date.today() < e['date'])
except StopIteration:
    print 'Freedom!'
else:
    if os.environ.get('BLOCK_BUTTON') == '1':
        print "%s | %s" % (next_exam['time'], next_exam['location'])
    else:
        delta = next_exam['date'] - date.today()
        name = next_exam['name']

        time_delta = delta.days
        if time_delta == 1:
            name = name.upper()
        elif time_delta == 0:
            time = divmod(delta.seconds//60,  60)
            time_delta = "%d:%d" % time

        print '%s [%s]' % (name, time_delta)

